name: cv_robotics_lab21
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - ultralytics>=8.4
      - boxmot==25.0.0
      - opencv-python>=4.8
      - numpy
      - pyyaml
      - lap>=0.4.0
      - scipy
      - filterpy
      - matplotlib
      - pytest
